### ISSUE TITLE
Bump dependencies to dioxus 0.6

### ISSUE THREAD

**Issue by Emm** [dioxus-community/dioxus-use-mounted#4]
Now that dioxus 0.6 is out, it would be great to have a new release using it.

**Comment by Emm** [comment]
I have just tested `dioxus-lazy` with dioxus 0.6, using Git versions for the dependencies, and it seems to work fine. I'll be happy to open PRs for `dioxus-resize-observer` and `dioxus-lazy` if you publish to crates.io (unless you prefer to handle this yourself)

**Comment by marc2332** [comment]
> I have just tested `dioxus-lazy` with dioxus 0.6, using Git versions for the dependencies, and it seems to work fine. I'll be happy to open PRs for `dioxus-resize-observer` and `dioxus-lazy` if you publish to crates.io (unless you prefer to handle this yourself)

Yeah, feel free to open PRs, I'll be sure to review them asap and make a release as well 😄
